services:
  postgres:
    container_name: 'senior-project-postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=health-tracking'
      - 'POSTGRES_PASSWORD=123456'
    ports:
      - '5432:5432'
